version: '3'

services:
    postgres:
        image: postgres:alpine
        container_name: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: fujitsu
        networks:
            - app-network
    
    apiserver:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: apiserver
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - app-network
        environment:
            spring.datasource.url: jdbc:postgresql://postgres:5432/fujitsu

            
    webserver:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8081:80"
        depends_on:
            - apiserver
        networks:
            - app-network
        
networks:
    app-network:
        driver: bridge
